# Generated by Django 4.2.7 on 2023-11-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='last_reminder_sent',
            field=models.DateField(blank=True, null=True, verbose_name='Дата последнего напоминания'),
        ),
    ]
